#!/bin/sh
# From Gerrit Code Review 3.1.0
#
# Part of Gerrit Code Review (https://www.gerritcodereview.com/)
#
# Copyright (C) 2009 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# get commit msg
# commit_msg=`cat $1` #get all commit message
if [[ $CI_COMMIT_MESSAGE ]]; then
    msg=$CI_COMMIT_MESSAGE
else
    #read msg < .git/COMMIT_EDITMSG
    msg=$(cat "$1")
fi
# echo -e "\033[31m The commit msg: \033[0m $msg"
echo -e "The commit msg:\n\n$msg"
echo -e "\033[32m \n ****HOOK LOG****\n \033[0m"

redmineid=$(echo "$msg" | grep "redmine: #")
echo -e " The redmine content: $redmineid"

ext_redmineid=$(echo "$msg" | grep "ext-redmine: #")
echo -e " The ext_redmine content: $ext_redmineid"


#if [[ $string == mas* ]];  start with 'mas' in string
# get branch
remote_branch=`git rev-parse --abbrev-ref --symbolic-full-name @{u}`
echo -e " remote_branch is $remote_branch"

local_branch=`git symbolic-ref --short -q HEAD`
echo -e " local_branch is $local_branch"

if [[ $remote_branch ]]; then
    branch=$remote_branch
else
    branch=$local_branch
fi
echo -e " checked branch is $branch"

# if the msg is merge then skip it
mergePattern='^Merge '
if [[ $msg =~ $mergePattern ]]; then
    echo -e "\033[32m skip the merge, commit success! \033[0m"
    exit 0
fi
# check the commit msg

pattern_redmine='^redmine: #[0-9]+'
pattern_ext_redmine='^ext-redmine: #[0-9]+'
pattern_header='^\[(bug|new|opt|chore)\]\[[a-zA-Z0-9_ ]+\].'


#if [[ $branch == *"$br1"* || $branch == *"$br2"* ]]; then
if [[ "$branch" == *"main"* || "$branch" == *"release/"* ]]; then
    echo -e "\033[32m ******** \033[0m"
    if [[ $msg =~ $pattern_header && ($redmineid =~ $pattern_redmine || $ext_redmineid =~ $pattern_ext_redmine) ]]; then
        echo -e "\033[32m commit success! \033[0m"
    else
        echo -e "\033[31m Error: must be correct tags and redmineid or tapdid \033[m"
        echo -e "\033[31m eg: [bug|new|opt|chore][module_name] Fixed games assert when start \033[m"
        echo -e "\033[31m eg: redmine: #1999, REDMINE-1999 \033[m"
        echo -e "\033[31m eg: ext-redmine: #2356|ext-redmine: #2356 \033[m"
        exit 1
    fi
else
    if [[ $msg =~ $pattern_header ]]; then
        echo -e "\033[32m commit success! \033[0m"
    else
        echo -e "\033[31m Error: the commit message is irregular \033[m"
        echo -e "\033[31m Error: must be four correct tags [bug|new|opt|chore]\033[m"
        echo -e "\033[31m eg: [bug|new|opt|chore][module_name] Fixed watchdemo crush bug \033[m"
        exit 1
    fi
fi


# avoid [[ which is not POSIX sh.
if test "$#" != 1 ; then
  echo "$0 requires an argument."
  exit 1
fi

if test ! -f "$1" ; then
  echo "file does not exist: $1"
  exit 1
fi

# Do not create a change id if requested
if test "false" = "`git config --bool --get gerrit.createChangeId`" ; then
  exit 0
fi

# $RANDOM will be undefined if not using bash, so don't use set -u
random=$( (whoami ; hostname ; date; cat $1 ; echo $RANDOM) | git hash-object --stdin)
dest="$1.tmp.${random}"

trap 'rm -f "${dest}"' EXIT

if ! git stripspace --strip-comments < "$1" > "${dest}" ; then
   echo "cannot strip comments from $1"
   exit 1
fi

if test ! -s "${dest}" ; then
  echo "file is empty: $1"
  exit 1
fi

# Avoid the --in-place option which only appeared in Git 2.8
# Avoid the --if-exists option which only appeared in Git 2.15
if ! git -c trailer.ifexists=doNothing interpret-trailers \
      --trailer "Change-Id: I${random}" < "$1" > "${dest}" ; then
  echo "cannot insert change-id line in $1"
  exit 1
fi

if ! mv "${dest}" "$1" ; then
  echo "cannot mv ${dest} to $1"
  exit 1
fi
