import os
from building import *

cwd = GetCurrentDir()
objs = []
list = os.listdir(cwd)

# Add SDK
Import('SIFLI_SDK')


# Add lcpu patch
objs.extend(SConscript(os.path.join(SIFLI_SDK, 'example/rom_bin/lcpu_general_ble_img/SConscript'), variant_dir="lcpu_patch", duplicate=0))

objs.extend(SConscript(os.path.join(SIFLI_SDK, 'SConscript'), variant_dir="sifli_sdk", duplicate=0))

# Add application source code
# workaround: src folder must be created before resource/strings folder is used, otherwise langpack would not be built
Execute(Mkdir('src'))
objs.extend(SConscript(os.path.join(cwd, '../../src/hcpu/SConscript'), variant_dir="src", duplicate=0))

Return('objs')
