# for module compiling
import os
from building import *


cwd = GetCurrentDir()

src = []

cwd = GetCurrentDir()  # get current dir path
objs_no_ezip = []
objs_ezip = []
objs_no_ezip += Glob('*.png')
objs_ezip += Glob('*ezip/*.png')

if 16 == GetConfigValue('LV_COLOR_DEPTH'):
    img_flags = '-rgb565'
else:
    img_flags = '-rgb888'

src = Env.ImgResource(objs_no_ezip, img_flags+' -cfile 1 -dpt 1')
src += Env.ImgResource(objs_ezip, img_flags+' -cfile 2 -dpt 1')

group = DefineGroup('asset', src, depend = ['PKG_USING_LITTLEVGL2RTT'])  

Return ('group')