/*
 * SPDX-FileCopyrightText: 2019-2025 SiFli Technologies(Nanjing) Co., Ltd
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef __LCPU_CONFIG_TYPE_INT_H
#define __LCPU_CONFIG_TYPE_INT_H


/**
typedef struct
{
    uint32_t adc_cal;
    uint32_t sdadc_cal[2];
    uint8_t sn[128];
    uint16_t sn_len;
    uint8_t chip_rev;
    uint8_t reserved;
    uint32_t battery_a;
    uint32_t battery_b;
} LCPU_CONFIG_TYPE_T;
**/

#define LCPU_CONFIG_START_ADDR 0x20137000
#define LPCU_CONFIG_MAGIC_NUM 0x45457878

#define LCPU_ASSERT_INFO_ADDR  0x20137200
#define LPCU_ASSERT_OVER_FLAG  0xa5a5a5a5

#define LCPU_CONFIG_ROM_SIZE 0x9C

#define HAL_LCPU_CONFIG_ADC_CALIBRATION_ROM 0
#define LCPU_CONFIG_ADC_CALIBRATION_ROM_OFFSET 4
#define LCPU_CONFIG_ADC_CALIBRATION_ROM_LENGTH 4

#define HAL_LCPU_CONFIG_SDADC_CALIBRATION_ROM 1
#define LCPU_CONFIG_SDADC_CALIBRATION_ROM_OFFSET 8
#define LCPU_CONFIG_SDADC_CALIBRATION_ROM_LENGTH 8

#define HAL_LCPU_CONFIG_SN_ROM 2
#define LCPU_CONFIG_SN_ROM_OFFSET 16
#define LCPU_CONFIG_SN_ROM_LENGTH 128
#define LCPU_CONFIG_SN_LEN_ROM_OFFSET 144
#define LCPU_CONFIG_SN_LEN_ROM_LENGTH 2


#define HAL_LCPU_CONFIG_CHIP_REV_ROM 3
#define LCPU_CONFIG_CHIP_REV_ROM_OFFSET 146
#define LCPU_CONFIG_CHIP_REV_ROM_LENGTH 1

#define HAL_LCPU_CONFIG_BATTERY_CALIBRATION_ROM 4
#define LCPU_CONFIG_BATTERY_A_ROM_OFFSET 148
#define LCPU_CONFIG_BATTERY_A_ROM_LENGTH 4
#define LCPU_CONFIG_BATTERY_B_ROM_OFFSET 152
#define LCPU_CONFIG_BATTERY_B_ROM_LENGTH 4


#endif // __LCPU_CONFIG_TYPE_INT_H
